<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensajes [
  <!ELEMENT mensajes (mensaje+)>
  <!ELEMENT mensaje (de, para, hora, texto)>
  <!ELEMENT de (#PCDATA)>
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT hora (#PCDATA)>
  <!ELEMENT texto (#PCDATA)>
  <!ELEMENT strong (#PCDATA)>
  
]>

<mensajes>
  <mensaje>
    <de>Pepe (pepe@example.com)</de>
    <para>Juan (juan@example.com)</para>
    <hora>28/02/2011 17:48:23,61</hora>
    <texto>¿Hola, Juan, qué haces?</texto>
  </mensaje>
  <mensaje>
    <de>Juan (juan@example.com)</de>
    <para>Pepe (pepe@example.com)</para>
    <hora>28/02/2011 17:54:20,87</hora>
    <texto>Aquí, aprendiendo <strong>XML</strong></texto>
  </mensaje>
</mensajes>

<!-- En el código la estructura de como se recibían los mensajes en el dtd estaba incorrecta
pues la etiqueta "Mensaje" no existía, y esta es la que debe englobar a las etiquetas 
de, para, hora, texto. Hay un error más para con el elemento Strong, pues debe poder
introducirse dentro de "Texto", pero debe de ser opcional y no se como realizarlo.-->