=== MrKaleth/1-CFGS-DAM/Lenguaje de Marcas/Código VisualStudio/Lenguaje de Marcas/XML/Práctica1/Viaje.dtd
<!ELEMENT viaje (cliente, destinos)>
<!ELEMENT cliente (nombre, fecha_inicio, fecha_fin, origen)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destinos (destino+)>
<!ELEMENT destino (ciudad, hotel, noches)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT hotel (#PCDATA)>
<!ELEMENT noches (#PCDATA)>

=== MrKaleth/1-CFGS-DAM/Lenguaje de Marcas/Código VisualStudio/Lenguaje de Marcas/XML/Práctica1/Viaje.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE viaje SYSTEM "viaje.dtd">
<viaje>
    <cliente>
        <nombre>Juan Pérez</nombre>
        <fecha_inicio>2025-01-01</fecha_inicio>
        <fecha_fin>2025-01-10</fecha_fin>
        <origen>Madrid</origen>
    </cliente>
    <destinos>
        <destino>
            <ciudad>Paris</ciudad>
            <hotel>Hotel de París</hotel>
            <noches>3</noches>
        </destino>
        <destino>
            <ciudad>Roma</ciudad>
            <hotel>Hotel Roma Centro</hotel>
            <noches>4</noches>
        </destino>
        <destino>
            <ciudad>Venecia</ciudad>
            <hotel>Hotel Veneciano</hotel>
            <noches>2</noches>
        </destino>
    </destinos>
</viaje>
