<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor, año)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
]>
<biblioteca>
    <libro>
        <titulo>1984</titulo>
        <autor>George Orwell</autor>
        <año>1949</año>
    </libro>
    <libro>
        <titulo>El Principito</titulo>
        <autor>Antoine de Saint-Exupéry</autor>
        <año>1943</año>
    </libro>
</biblioteca>